#
#
#
version: '3'


services:


  webserver_nginx:
    image: nginx:latest
    container_name: webserver_nginx
    networks:
      net-0:
    ports:
      - "8888:80"
    volumes:
      - ./www_site:/www_site
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - webserver_php
    labels:
      - "traefik.backend=webserver"
      - "traefik.docker.network=webserver_webLAN"
      #- "traefik.frontend.rule=PathPrefix:/yoloctf/;ReplacePathRegex: ^/yoloctf/(.*) /$$1"  
      - "traefik.frontend.rule=PathPrefix:/yoloctf/"      
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.default.protocol=http"


  webserver_php:
    image: php:7-fpm
    container_name: webserver_php
    volumes:
      - ./www_site:/www_site
    networks:
      net-0:




      
networks:
  net-0:
    driver: bridge