#
#
#
version: '3.3'

services:

  webserver_register_nginx:
    image: nginx:1.17
    container_name: webserver_register_nginx
    networks:
      traefikacme_ctf_register_lan:
      #traefik_ctf_register_lan:
      ctf_register_lan_php:
    volumes:
      - ./www_site:/www_site
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - webserver_register_php
    labels:
      - "traefik.backend=webserver"
      - "traefik.docker.network=traefikacme_ctf_register_lan"
      - "traefik.frontend.rule=Host:dayctf.iut-rt.net"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.default.protocol=http"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"



  webserver_register_php:
    image: php:7-fpm
    container_name: webserver_register_php
    env_file:
      - .env
    volumes:
      - ./www_site:/www_site
    networks:
      ctf_register_lan_php:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"


    

networks:
  traefik_ctf_register_lan:
    external: true
  traefikacme_ctf_register_lan:
    external: true
  ctf_register_lan_php:
    driver: bridge
