#
#
#
version: '3'


services:


  webserver_register_nginx:
    image: nginx:1.17
    container_name: webserver_register_nginx
    networks:
      ctf_register_lan:
      ctf_register_lan_php:
    volumes:
      - ./www_site:/www_site
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - webserver_register_php
    labels:
      - "traefik.backend=webserver"
      - "traefik.docker.network=webserver_webLAN"
      - "traefik.frontend.rule=PathPrefix:/"      
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.default.protocol=http"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  webserver_register_php:
    image: php:7-fpm
    container_name: webserver_register_php
    volumes:
      - ./www_site:/www_site
    networks:
      ctf_register_lan_php:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"


services:
  traefik:
    image: traefik:1.7
    restart: always
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8000:8000"
    networks:
      - ctf_register_lan
      - webserver_webLAN
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    container_name: traefik
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    

networks:
  webserver_webLAN:
    driver: bridge
  ctf_register_lan:
    driver: bridge
  ctf_register_lan_php:
    driver: bridge